apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
configMapGenerator:
- name: metallb-values
  files:
  - values.yaml
- name: metallb-config
  files:
  - config=metallb-config.yaml
configurations:
- kustomizeconfig.yaml