apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syno-btrfs-reclaim
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  protocol: iscsi
  csi.storage.k8s.io/fstype: btrfs
reclaimPolicy: Delete
allowVolumeExpansion: true
