apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidero-system
resources:
- environment/rpi4.yaml
- secret/ghcr.sops.yaml
- serverclass/raspberrypi-4gb.yaml
- serverclass/raspberrypi-8gb.yaml
- deployment.patch.yaml
- clusters
