---
recommender:
  enabled: true
  extraArgs:
    pod-recommendation-min-cpu-millicores: 15
    pod-recommendation-min-memory-mb: 50
    storage: prometheus
    prometheus-address: http://kps-prometheus.monitoring.svc.cluster.local:9090

updater:
  enabled: false

admissionController:
  enabled: false