apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr.io
      volumes:
      - name: tftp-folder
        emptyDir: { }
      initContainers:
      - image: ghcr.io/zebernst/raspberrypi4-uefi:v1.1.0-alpha.0-41-g7add479@sha256:b9a891cefd159b204a480b036d3f1c4b4f894beb2bf7db879f66a5ae6a798115
        imagePullPolicy: Always
        name: tftp-folder-setup
        command:
        - cp
        args:
        - -r
        - /tftp
        - /var/lib/sidero/
        volumeMounts:
        - mountPath: /var/lib/sidero/tftp
          name: tftp-folder
      containers:
      - name: manager
        volumeMounts:
        - mountPath: /var/lib/sidero/tftp
          name: tftp-folder