apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller.yaml
- csi-driver.yaml
- node.yaml
- snapshotter.yaml
- storage-classes/syno-btrfs.yaml
- storage-classes/syno-btrfs-reclaim.yaml
- storage-classes/syno-ext4.yaml
- storage-classes/syno-ext4-reclaim.yaml
- storage-classes/syno-snapshot.yaml

secretGenerator:
- name: client-info-secret
  files:
  - client-info.yml=client-info.enc.yaml