apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
- secret-cloudflare-api-token.yaml
- issuers/letsencrypt.yaml
- issuers/letsencrypt-staging.yaml
configMapGenerator:
- name: cert-manager-values
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml