apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
stringData:
    api-token: ENC[AES256_GCM,data:bqY045IFGlVtgUVgAOjhDjnJG+RXWOqU9kNSR1sa1IbdXFHClzXnaA==,iv:FDFHq4A52NsiPtJ8gMTQppYZqmctJ3W7Sl+gqQDH6TE=,tag:fSenAXIVezsjEY18KTHPRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1duclwfw6qyjzwjnw3frakh6j25ultdeszdr6csulgl3j0gqntpdqcxysgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaXRtUWh6T21wNHR5WlVn
            NHQ5L1JpcUFzN2VMK2hSSzQ5NnE3V2paQUNrCjREY0hQS3hGL1Z5QitWOFFRd1Jx
            RjJZOUQzcTEyQkE1MUk1ZDJwNEgvS0UKLS0tIGNmZjBWaWlVWWt4REFwR3pTRUtx
            djNEWC9HQWNtZGJPTVJLVlFCVE5vZFUKZxI2i04gWSW2RtEfJm9E9r/ggXxhfqVv
            jV5iUWEjpT3cpuikEETM917qduNcrhVQjoizj5c/TLIs9AwG0QkZ8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T18:00:47Z"
    mac: ENC[AES256_GCM,data:CooGe/FJZjwoHwNWLyJibSbKjnwcMkkz6UM8VpKjUP+L6kTdz0cUpcdxDNpWQeltk90AcN70sgmFSmxvjBL5P54/TJF7gQPpv5aAzEkABfoqY0PvPngNe6KL8rKN3KuhuvVE3zm6Ilo+iv5KqxboMhxU7FOEeDzrOQy6C6EoWpc=,iv:Nhg05cgpYF/1P0XrP3jwWEuJ8NsEGoJPix6QmlUECgE=,tag:cVB6HozXLn4mDj6GGxibuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
