apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:skdzY32Po6cafTzA9Xuaq9FRufI=,iv:gl9M/7xZHK1Erh7jNHQxR6zakFygRErRsyyUW0Cq2+Y=,tag:Bne6sI4hkE3O2JKJCNHguw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1duclwfw6qyjzwjnw3frakh6j25ultdeszdr6csulgl3j0gqntpdqcxysgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTlBZeWRoM1VuYSt6MlFY
            YVo0TkhLa1JOQzc3MlJmcTZZRGJOU2hoblZRCjgwQUhiOEI1V21BRXBaRnhxRDk3
            b3lqelZOb2hLT2JSVzIvUW90OWY3N1UKLS0tIGtaVDl0QTVoaTRZdlRoUzkrWU5L
            dUd6ajJaQUVHWXE1aFdvaFhoc1o1eDQKXHUHI5ZFH4GZwI52NS3PQ6YrdyuiFV+I
            3VgrMhK/zgpWc6AQ+fpVMBFYdxNKzTYMtthgrWet3CfwauUITEPdqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T18:19:04Z"
    mac: ENC[AES256_GCM,data:feGoB21Lx5XS++Rri53pc0oR18/BPyCUURimSZUlmwqb9oDShS0YshvYtafXrFEGFYxbFdZJTk6zhbZg4W1RaaBKn5BM5xUXAuvTzQ3yeCFxyI7itRIfgBQqIEU9PKEVawVZ03qBsxakWSaPAnUcTwd3uwcSOWtfvD5xvzTS1VE=,iv:d/tRmY/nOx2AaQgn+z9Tm0kaD4JWpZ1Pd3f5C74YZzY=,tag:PgJK23j9lOfMvWiowRCzuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
