apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:skdzY32Po6cafTzA9Xuaq9FRufI=,iv:gl9M/7xZHK1Erh7jNHQxR6zakFygRErRsyyUW0Cq2+Y=,tag:Bne6sI4hkE3O2JKJCNHguw==,type:str]
    DOMAIN_NAME: ENC[AES256_GCM,data:p4HDpAd2VnJCGYVHR0Q=,iv:uG3fB5wB3dYXUyodgKiVZ1Enl583n63+3AMdAI8NjHY=,tag:mLN5NOX+Ts2jU66aP/IeCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1duclwfw6qyjzwjnw3frakh6j25ultdeszdr6csulgl3j0gqntpdqcxysgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTlBZeWRoM1VuYSt6MlFY
            YVo0TkhLa1JOQzc3MlJmcTZZRGJOU2hoblZRCjgwQUhiOEI1V21BRXBaRnhxRDk3
            b3lqelZOb2hLT2JSVzIvUW90OWY3N1UKLS0tIGtaVDl0QTVoaTRZdlRoUzkrWU5L
            dUd6ajJaQUVHWXE1aFdvaFhoc1o1eDQKXHUHI5ZFH4GZwI52NS3PQ6YrdyuiFV+I
            3VgrMhK/zgpWc6AQ+fpVMBFYdxNKzTYMtthgrWet3CfwauUITEPdqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-01T19:06:04Z"
    mac: ENC[AES256_GCM,data:a5zqhP7cbov4lZ5WS+uD2NwEmi9J9B2FBln4Ze2axfgkKUVdbxJqgGyb5xQZvQpLzhFqAGrdmRv7ledG2tgdJl7rTqXS0Y7ZlWOIke2QeDnfbfB7wXb3BK2T5WOegukU1L+4bJNO/Ou60y9XsL194HU1X5KhCY6bLYmF8tm2RFM=,iv:cViNwK2dtgwLhr43+hOuLy8EO5vYTtG4dI5kYqb4Dxs=,tag:Haj59oXVOdp+MjGcOfxWsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
