apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster.yaml
- machinedeployment.yaml
- metalcluster.yaml
- metalmachinetemplate-controlplane.yaml
- metalmachinetemplate-workers.yaml
- talosconfigtemplate.yaml
- taloscontrolplane.yaml