---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: olympus-workers
  namespace: sidero-system
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.1.0
      configPatches:
      - op: add
        path: /machine/install/extensions
        value:
        - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: true