---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls.acme-wildcard
  namespace: kube-system
spec:
  secretName: tls.acme-wildcard-secret
  commonName: "*.${DOMAIN_NAME}"
  dnsNames:
  - "${DOMAIN_NAME}"
  - "*.${DOMAIN_NAME}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
