apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi
resources:
- controller.yaml
- csi-driver.yaml
- node.yaml
- snapshotter.yaml
- storage-classes/synology-lun.yaml
- storage-classes/synology-lun-snapshot.yaml

secretGenerator:
- name: client-info-secret
  files:
  - client-info.yaml=client-info.enc.yaml